// ============================================================================
// wasm_encoder.ts — direct IR → Wasm binary encoder
//
// Bypasses the WAT text format entirely, producing a valid WasmGC binary from
// our IR. This is necessary because wabt npm 1.0.39 does not support WasmGC
// nullable refs ((ref null $T)) or anyref in WAT text, even with gc:true.
//
// Supported IR ops (complete set generated by our compiler):
//   unreachable, return, block, loop, if, br, br_if, call,
//   local.get, local.set, string.const (→ i64.const),
//   i32.const, i32.eqz, i32.wrap_i64,
//   i64.const, i64.eq, i64.ne, i64.lt_s, i64.gt_s, i64.le_s, i64.ge_s,
//   i64.add, i64.sub, i64.mul, i64.div_s, i64.rem_s,
//   f64.const, f64.neg, f64.eq, f64.ne, f64.lt, f64.gt, f64.le, f64.ge,
//   f64.add, f64.sub, f64.mul, f64.div,
//   struct.new, struct.get, struct.set,
//   array.new_default, array.new_fixed, array.get, array.set
// ============================================================================

// ---------------------------------------------------------------------------
// LEB128 utilities
// ---------------------------------------------------------------------------

function uleb128(n: number): number[] {
  const out: number[] = [];
  do {
    let byte = n & 0x7f;
    n >>>= 7;
    if (n !== 0) byte |= 0x80;
    out.push(byte);
  } while (n !== 0);
  return out;
}

function sleb128(n: number): number[] {
  const out: number[] = [];
  let more = true;
  while (more) {
    let byte = n & 0x7f;
    n >>= 7; // arithmetic shift
    const signBit = (byte & 0x40) !== 0;
    if ((n === 0 && !signBit) || (n === -1 && signBit)) {
      more = false;
    } else {
      byte |= 0x80;
    }
    out.push(byte);
  }
  return out;
}

// i64 values in IR come as JS numbers (the compiler uses Number for i64.const,
// since BigInt is not supported in JSON). We encode them as sleb128.
// JS numbers can exactly represent integers up to 2^53, which covers all
// literal integer values a JPL program would use.
function sleb128_i64(n: number): number[] {
  // For small values, sleb128 of a number works fine.
  // For negative values (like -1 used in negation), n will be negative.
  return sleb128(n);
}

function f64Bytes(v: number): number[] {
  const buf = new ArrayBuffer(8);
  new DataView(buf).setFloat64(0, v, true); // little-endian
  return Array.from(new Uint8Array(buf));
}

// ---------------------------------------------------------------------------
// Section builder helpers
// ---------------------------------------------------------------------------

function vec(items: number[][]): number[] {
  return [...uleb128(items.length), ...items.flat()];
}

function section(id: number, content: number[]): number[] {
  return [id, ...uleb128(content.length), ...content];
}

function nameBytes(s: string): number[] {
  const bytes = new TextEncoder().encode(s);
  return [...uleb128(bytes.length), ...bytes];
}

// ---------------------------------------------------------------------------
// Value type encoding
// ---------------------------------------------------------------------------
// IR valtype is either a string ("i64","f64","i32") or
// {ref: string, nullable: boolean} where ref is "$typeName" or "any".

function encodeValType(t: unknown, typeIdx: (name: string) => number): number[] {
  if (typeof t === "string") {
    if (t === "i64") return [0x7e];
    if (t === "f64") return [0x7c];
    if (t === "i32") return [0x7f];
    throw new Error(`Unknown valtype string: ${t}`);
  }
  const rt = t as { ref: string; nullable: boolean };
  if (rt.ref === "any") {
    // anyref = 0x6E (nullable any is the standard ref type for anyref)
    return [0x6e];
  }
  const idx = typeIdx(rt.ref);
  if (rt.nullable) {
    return [0x63, ...uleb128(idx)]; // (ref null $T)
  } else {
    return [0x64, ...uleb128(idx)]; // (ref $T)
  }
}

// Canonical string key for a func signature (for deduplication).
function funcTypeSig(params: unknown[], results: unknown[]): string {
  return JSON.stringify({ params, results });
}

// ---------------------------------------------------------------------------
// Main encoder
// ---------------------------------------------------------------------------

export function encodeIR(ir: any): Uint8Array {
  // ── 1. Build type registry ────────────────────────────────────────────────
  // GC struct/array types come first (in IR order), then function types.

  const gcTypes: any[] = ir.types ?? []; // [{id, kind, ...}]
  const gcTypeIndex = new Map<string, number>(); // "$name" → index
  gcTypes.forEach((t: any, i: number) => gcTypeIndex.set(t.id, i));

  const typeIdx = (name: string): number => {
    const i = gcTypeIndex.get(name);
    if (i === undefined) throw new Error(`Unknown type: ${name}`);
    return i;
  };

  // Collect all function signatures, deduplicated.
  // funcTypeMap: sig → index-into-allTypeEntries (offset by gcTypes.length)
  const funcTypeSigs: string[] = [];
  const funcTypeDefs: { params: unknown[]; results: unknown[] }[] = [];
  const funcTypeMap = new Map<string, number>(); // sig → absolute type index

  function ensureFuncType(params: unknown[], results: unknown[]): number {
    const sig = funcTypeSig(params, results);
    if (funcTypeMap.has(sig)) return funcTypeMap.get(sig)!;
    const idx = gcTypes.length + funcTypeSigs.length;
    funcTypeSigs.push(sig);
    funcTypeDefs.push({ params, results });
    funcTypeMap.set(sig, idx);
    return idx;
  }

  // Assign type indices to imports.
  const imports: any[] = ir.imports ?? [];
  const importTypeIndices: number[] = imports.map((imp: any) =>
    ensureFuncType(imp.params ?? [], imp.results ?? [])
  );

  // Assign type indices to user funcs.
  const funcs: any[] = ir.funcs ?? [];
  const funcTypeIndices: number[] = funcs.map((fn: any) =>
    ensureFuncType(
      (fn.params ?? []).map((p: any) => p.type),
      fn.results ?? []
    )
  );

  // ── 2. Build function index registry ──────────────────────────────────────
  // Wasm function space: imports first, then user funcs.
  const funcIndex = new Map<string, number>();
  imports.forEach((imp: any, i: number) => {
    // IR uses "$host_show_i64" etc. as function names
    funcIndex.set(imp.as, i);
  });
  funcs.forEach((fn: any, i: number) => {
    funcIndex.set(fn.name, imports.length + i);
  });

  // ── 3. Encode type section ─────────────────────────────────────────────────
  const allTypeCount = gcTypes.length + funcTypeDefs.length;
  const typeEntries: number[] = [];
  typeEntries.push(...uleb128(allTypeCount));

  // GC types
  for (const t of gcTypes) {
    if (t.kind === "struct") {
      typeEntries.push(0x5f); // struct
      typeEntries.push(...uleb128(t.fields.length));
      for (const f of t.fields) {
        typeEntries.push(...encodeValType(f.type, typeIdx));
        typeEntries.push(f.mutability === "mut" ? 1 : 0);
      }
    } else if (t.kind === "array") {
      typeEntries.push(0x5e); // array
      typeEntries.push(...encodeValType(t.element, typeIdx));
      typeEntries.push(t.mutability === "mut" ? 1 : 0);
    } else {
      throw new Error(`Unknown GC type kind: ${t.kind}`);
    }
  }

  // Function types
  for (const ft of funcTypeDefs) {
    typeEntries.push(0x60); // func
    typeEntries.push(...uleb128(ft.params.length));
    for (const p of ft.params) {
      typeEntries.push(...encodeValType(p, typeIdx));
    }
    typeEntries.push(...uleb128(ft.results.length));
    for (const r of ft.results) {
      typeEntries.push(...encodeValType(r, typeIdx));
    }
  }

  const typeSec = section(1, typeEntries);

  // ── 4. Encode import section ───────────────────────────────────────────────
  const importEntries: number[][] = imports.map((imp: any, i: number) => {
    const modName = nameBytes(imp.module);
    const fieldName = nameBytes(imp.name);
    const typeIndex = uleb128(importTypeIndices[i]!);
    return [...modName, ...fieldName, 0x00, ...typeIndex]; // 0x00 = function import
  });
  const importSec = section(2, vec(importEntries));

  // ── 5. Encode function section ─────────────────────────────────────────────
  const funcSec = section(3, [
    ...uleb128(funcs.length),
    ...funcs.flatMap((_fn: any, i: number) => uleb128(funcTypeIndices[i]!)),
  ]);

  // ── 6. Encode export section ───────────────────────────────────────────────
  // Only export $main (the last function in ir.funcs).
  const mainIdx = funcs.findIndex((fn: any) => fn.name === "$main");
  if (mainIdx === -1) throw new Error("No $main function in IR");
  const mainFuncIdx = imports.length + mainIdx;
  const exportSec = section(7, [
    ...uleb128(1), // 1 export
    ...nameBytes("main"),
    0x00, // function export
    ...uleb128(mainFuncIdx),
  ]);

  // ── 7. Encode code section ─────────────────────────────────────────────────
  const codeBodies: number[][] = funcs.map((fn: any) =>
    encodeFuncBody(fn, funcIndex, typeIdx)
  );
  const codeSec = section(10, vec(codeBodies));

  // ── 8. Assemble binary ─────────────────────────────────────────────────────
  const magic = [0x00, 0x61, 0x73, 0x6d]; // \0asm
  const version = [0x01, 0x00, 0x00, 0x00];
  const binary = new Uint8Array([
    ...magic, ...version,
    ...typeSec, ...importSec, ...funcSec, ...exportSec, ...codeSec,
  ]);
  return binary;
}

// ---------------------------------------------------------------------------
// Function body encoder
// ---------------------------------------------------------------------------

function encodeFuncBody(
  fn: any,
  funcIndex: Map<string, number>,
  typeIdx: (name: string) => number
): number[] {
  // Build local variable index map: params first, then locals.
  const localIndex = new Map<string, number>();
  let nextIdx = 0;
  for (const p of fn.params ?? []) {
    localIndex.set(p.name, nextIdx++);
  }
  for (const l of fn.locals ?? []) {
    localIndex.set(l.name, nextIdx++);
  }

  // Encode locals declaration (only the non-param locals).
  // Each local is its own group of 1 for simplicity.
  const localDecls: number[] = [];
  const fnLocals: any[] = fn.locals ?? [];
  localDecls.push(...uleb128(fnLocals.length)); // number of local groups
  for (const l of fnLocals) {
    localDecls.push(...uleb128(1)); // count = 1
    localDecls.push(...encodeValType(l.type, typeIdx));
  }

  // Encode body instructions.
  const labelStack: (string | null)[] = [];
  const body = encodeInstrs(fn.body ?? [], localIndex, funcIndex, typeIdx, labelStack);
  body.push(0x0b); // end

  const content = [...localDecls, ...body];
  return [...uleb128(content.length), ...content];
}

// ---------------------------------------------------------------------------
// Instruction encoder (recursive for nested blocks)
// ---------------------------------------------------------------------------

function encodeInstrs(
  instrs: any[],
  localIndex: Map<string, number>,
  funcIndex: Map<string, number>,
  typeIdx: (name: string) => number,
  labelStack: (string | null)[]
): number[] {
  const out: number[] = [];

  for (const instr of instrs) {
    encodeInstr(instr, out, localIndex, funcIndex, typeIdx, labelStack);
  }

  return out;
}

function encodeInstr(
  instr: any,
  out: number[],
  localIndex: Map<string, number>,
  funcIndex: Map<string, number>,
  typeIdx: (name: string) => number,
  labelStack: (string | null)[]
): void {
  const op: string = instr.op;

  switch (op) {
    case "unreachable":
      out.push(0x00);
      break;

    case "return":
      out.push(0x0f);
      break;

    case "block": {
      out.push(0x02); // block
      out.push(0x40); // void block type (blocks are always void in our IR)
      const label: string = instr.label;
      labelStack.push(label);
      const body = encodeInstrs(instr.body, localIndex, funcIndex, typeIdx, labelStack);
      out.push(...body);
      out.push(0x0b); // end
      labelStack.pop();
      break;
    }

    case "loop": {
      out.push(0x03); // loop
      out.push(0x40); // void block type
      const label: string = instr.label;
      labelStack.push(label);
      const body = encodeInstrs(instr.body, localIndex, funcIndex, typeIdx, labelStack);
      out.push(...body);
      out.push(0x0b); // end
      labelStack.pop();
      break;
    }

    case "if": {
      out.push(0x04); // if
      // Block type: void (0x40), i32 (0x7F), i64 (0x7E), f64 (0x7C)
      const result: string | undefined = instr.result;
      if (!result) {
        out.push(0x40);
      } else if (result === "i64") {
        out.push(0x7e);
      } else if (result === "i32") {
        out.push(0x7f);
      } else if (result === "f64") {
        out.push(0x7c);
      } else {
        throw new Error(`Unknown if result type: ${result}`);
      }
      // Push null as sentinel (if blocks can't be br targets in our IR)
      labelStack.push(null);
      const thenBody = encodeInstrs(instr.then ?? [], localIndex, funcIndex, typeIdx, labelStack);
      out.push(...thenBody);
      if (instr.else && instr.else.length > 0) {
        out.push(0x05); // else
        const elseBody = encodeInstrs(instr.else, localIndex, funcIndex, typeIdx, labelStack);
        out.push(...elseBody);
      }
      out.push(0x0b); // end
      labelStack.pop();
      break;
    }

    case "br": {
      out.push(0x0c);
      out.push(...uleb128(resolveLabelDepth(instr.label, labelStack)));
      break;
    }

    case "br_if": {
      out.push(0x0d);
      out.push(...uleb128(resolveLabelDepth(instr.label, labelStack)));
      break;
    }

    case "call": {
      const idx = funcIndex.get(instr.func);
      if (idx === undefined) throw new Error(`Unknown function: ${instr.func}`);
      out.push(0x10, ...uleb128(idx));
      break;
    }

    case "local.get": {
      const idx = localIndex.get(instr.local);
      if (idx === undefined) throw new Error(`Unknown local: ${instr.local}`);
      out.push(0x20, ...uleb128(idx));
      break;
    }

    case "local.set": {
      const idx = localIndex.get(instr.local);
      if (idx === undefined) throw new Error(`Unknown local: ${instr.local}`);
      out.push(0x21, ...uleb128(idx));
      break;
    }

    case "i32.const":
      out.push(0x41, ...sleb128(instr.value as number));
      break;

    case "i64.const":
      out.push(0x42, ...sleb128_i64(instr.value as number));
      break;

    case "string.const":
      // String constants are indices into the strings table — emit as i64.const.
      out.push(0x42, ...sleb128_i64(instr.index as number));
      break;

    case "f64.const":
      out.push(0x44, ...f64Bytes(instr.value as number));
      break;

    // i32 ops
    case "i32.eqz":    out.push(0x45); break;
    case "i32.wrap_i64": out.push(0xa7); break;

    // i64 comparisons
    case "i64.eq":  out.push(0x51); break;
    case "i64.ne":  out.push(0x52); break;
    case "i64.lt_s": out.push(0x53); break;
    case "i64.gt_s": out.push(0x55); break;
    case "i64.le_s": out.push(0x57); break;
    case "i64.ge_s": out.push(0x59); break;

    // i64 arithmetic
    case "i64.add":   out.push(0x7c); break;
    case "i64.sub":   out.push(0x7d); break;
    case "i64.mul":   out.push(0x7e); break;
    case "i64.div_s": out.push(0x7f); break;
    case "i64.rem_s": out.push(0x81); break;

    // f64 comparisons
    case "f64.eq":  out.push(0x61); break;
    case "f64.ne":  out.push(0x62); break;
    case "f64.lt":  out.push(0x63); break;
    case "f64.gt":  out.push(0x64); break;
    case "f64.le":  out.push(0x65); break;
    case "f64.ge":  out.push(0x66); break;

    // f64 arithmetic
    case "f64.neg": out.push(0x9a); break;
    case "f64.add": out.push(0xa0); break;
    case "f64.sub": out.push(0xa1); break;
    case "f64.mul": out.push(0xa2); break;
    case "f64.div": out.push(0xa3); break;

    // GC instructions (prefix 0xFB)
    case "struct.new": {
      out.push(0xfb, 0x00, ...uleb128(typeIdx(instr.type)));
      break;
    }

    case "struct.get": {
      out.push(0xfb, 0x02, ...uleb128(typeIdx(instr.type)), ...uleb128(instr.field as number));
      break;
    }

    case "struct.set": {
      out.push(0xfb, 0x05, ...uleb128(typeIdx(instr.type)), ...uleb128(instr.field as number));
      break;
    }

    case "array.new_default": {
      out.push(0xfb, 0x07, ...uleb128(typeIdx(instr.type)));
      break;
    }

    case "array.new_fixed": {
      out.push(0xfb, 0x08, ...uleb128(typeIdx(instr.type)), ...uleb128(instr.length as number));
      break;
    }

    case "array.get": {
      out.push(0xfb, 0x0b, ...uleb128(typeIdx(instr.type)));
      break;
    }

    case "array.set": {
      out.push(0xfb, 0x0e, ...uleb128(typeIdx(instr.type)));
      break;
    }

    default:
      throw new Error(`Unknown IR op: ${op}`);
  }
}

// ---------------------------------------------------------------------------
// Label depth resolution
// ---------------------------------------------------------------------------

function resolveLabelDepth(label: string, stack: (string | null)[]): number {
  // Search from the top (innermost = depth 0).
  for (let i = stack.length - 1; i >= 0; i--) {
    if (stack[i] === label) {
      return stack.length - 1 - i;
    }
  }
  throw new Error(`Unknown label: ${label}. Stack: [${stack.join(", ")}]`);
}
